# Generated by Django 5.1.3 on 2025-02-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConferenceSession',
        ),
    ]
