# Generated by Django 5.1.3 on 2025-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyFile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="myfiles")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
