# Generated by Django 5.1.3 on 2025-02-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_myfile_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfile",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
