# Generated by Django 5.1.3 on 2025-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_myfile_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfile",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
