# Generated by Django 5.1.3 on 2025-02-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_myfile_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfile",
            name="file",
            field=models.FileField(upload_to="myfile"),
        ),
    ]
